name: hail
dependencies:
- python=3.6
- Sphinx=1.7
- sphinxcontrib
- conda-forge::nbsphinx
- conda-forge::sphinx_rtd_theme
- numpy
- pandas
- matplotlib
- seaborn
- bokeh
- jupyter
- pip
- pytest
- pip:
    - parsimonious
    - ipykernel
    - pytest-xdist
